# Generated by Django 2.1.2 on 2018-10-19 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disasters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=15)),
                ('date_published', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
