# Generated by Django 2.1.2 on 2018-10-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasters',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
