# Generated by Django 2.1.2 on 2018-10-19 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181019_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disasters',
            name='date_published',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 19, 17, 19, 18, 111265)),
        ),
    ]
