# Generated by Django 2.1.2 on 2018-10-22 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181019_1719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='disasters',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
