# Generated by Django 2.1.2 on 2018-10-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20181023_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personfound',
            name='disaster',
            field=models.CharField(choices=[('KL', 'Kerala Floods'), ('HM', 'Hurrincane Micheal'), ('CT', 'Cyclone Titli'), ('IT', 'Indonesian Tsunami')], default='KL', max_length=50),
        ),
    ]
